#!/bin/bash
export VOLUMES=${1:-localhost:3001}
export DB=${2:-/tmp/cachedb/}
export TYPE=master
export PORT=${PORT:-3000}
uwsgi --http :$PORT --wsgi-file src/server.py --callable master --master --processes 4

