#!/bin/bash
export VOLUME=${1:-/tmp/volume1/}
export TYPE=volume
export PORT=${PORT:-3001}

./precreate.py $VOLUME

CONF=$(mktemp)
echo "
daemon off;
worker_processes 1;

error_log /dev/stderr;
pid $VOLUME/tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  client_body_temp_path $VOLUME/body_temp;

  server {
    client_max_body_size 0;
    listen $PORT default_server;
    location / {
      root $VOLUME;
      dav_methods PUT DELETE;
    }
  }
}
" > $CONF
nginx -c $CONF -p $VOLUME/tmp

