#!/bin/bash -e
export VOLUME=${1:-/tmp/volume1/}
export SUBVOLUMES=${2:-1}
export TYPE=volume
export PORT=${PORT:-3001}

# create 65536 directories for files
create_directories() {
  echo -n "creating directories for $1..."
  for I in 0 1 2 3 4 5 6 7 8 9 a b c d e f
  do
    mkdir -m 777 -p $1/${I}{0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f}/{0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f}{0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f}
  done
  echo "done"
}

if [ "$SUBVOLUMES" -eq "1" ]; then
  create_directories $VOLUME
else
  for VV in $(seq 0 $(($SUBVOLUMES - 1)))
  do
    create_directories $VOLUME/sv0${VV}
  done
fi


CONF=$(mktemp)
echo "
daemon off; # docker
#worker_rlimit_nofile 100000;
worker_processes auto;
pcre_jit on;

error_log /dev/stderr;
pid $VOLUME/nginx.pid;

events {
  #use epoll;
  multi_accept on;
  accept_mutex off;
  worker_connections 4096;
}

http {
  sendfile on;
  sendfile_max_chunk 1024k;

  tcp_nopush on;
  tcp_nodelay on;

  open_file_cache off;
  types_hash_max_size 2048;

  server_tokens off;

  default_type application/octet-stream;

  error_log /dev/stderr error; # docker

  server {
    listen $PORT default_server backlog=4096;
    location / {
      root $VOLUME;

      client_body_temp_path $VOLUME/body_temp;
      client_max_body_size 0;

      # this causes tests to fail
      #client_body_buffer_size 0;

      dav_methods PUT DELETE;
      dav_access group:rw all:r;

      autoindex on;
      autoindex_format json;
    }
  }
}
" > $CONF
echo "starting nginx on $PORT"
nginx -c $CONF -p $VOLUME/tmp

