#!/bin/bash
export VOLUME=${1:-/tmp/volume1/}
export TYPE=volume
export HOST=${HOST:-$(hostname)}
export PORT=${PORT:-3001}
uwsgi --http :$PORT --wsgi-file src/server.py --callable volume --master --processes 4

