name: Tests

on: [push, pull_request]

jobs:
  unit:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Install nginx
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install nginx build-essential
    - name: Set log permissions
      run: |
        sudo mkdir -p /var/log/nginx
        sudo chmod 777 /var/log/nginx /var/log/nginx/*
    - name: Unit Tests
      run: go test -v src/lib_test.go src/lib.go
    - name: Install Python Requirements
      run: pip3 install --no-cache-dir -r requirements.txt
    - name: Thrasher Test
      run: |
        (./tools/bringup.sh &)
        ./tools/test.py
        ./tools/s3test.py
        go run tools/thrasher.go
        ./tools/rtest.sh
